language: java

jdk:
  - openjdk8
  
notifications:
  irc:
    channels:
      - "chat.freenode.net#stripes"
    on_success: always
    on_failure: always

install: true
script: 
  - mvn clean install javadoc:aggregate
